#!/bin/bash

set -eu

function test {
  local ver=$1; shift
  local cmd="docker run -t -u $(id -u):$(id -g) -v $(pwd):/v -w /v --rm crystallang/crystal:$ver crystal spec -v $@"
  echo "----------------------------------------------------------------------"
  echo "[$ver] $cmd"
  echo "----------------------------------------------------------------------"
  $cmd
}

test 0.27.2
test 0.33.0
test 0.34.0 --exclude-warnings lib
test 0.35.1 --exclude-warnings lib
